### ISSUE TITLE
npm test fails

### ISSUE THREAD

**Issue by anselmbradford** [rstacruz/mocha-jsdom#10]
`npm install && npm test` fails with:

```
  globalize
    1) "before all" hook

  jquery
    ✓ creating elements works
    ✓ lookup works

  rerequire
    ✓ has a fixture that works
    ✓ has a fixture that really works
    ✓ works 5x

  simple
    ✓ has document
    2) has history

  skipWindowCheck: true
    ✓ does not throw errors

  standard
    3) is conformed to

  check useEach false (default)
    ✓ check that html body is empty
    ✓ accepts an html body
    ✓ has document persisting across tests

  check useEach true
    ✓ check that html body is empty
    ✓ accepts an html body
    ✓ changes to the dom do not persist between tests


  13 passing (5s)
  3 failing

  1) globalize "before all" hook:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
      at Object.done (index.js:70:7)
      at node_modules/jsdom/lib/jsdom.js:271:18

  2) simple has history:

      AssertionError: expected '/a/b/c' to deeply equal 'file:///a/b/c'
      + expected - actual

      -/a/b/c
      +file:///a/b/c

      at Context.<anonymous> (test/simple.js:15:27)

  3) standard is conformed to:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.




npm ERR! Test failed.  See above for more details.
```

**Comment by anselmbradford** [comment]
Fixed in https://github.com/rstacruz/mocha-jsdom/pull/12
