### ISSUE TITLE
It seems no work when use mocha-jsdom when depend lib have 'window' variable.

### ISSUE THREAD

**Issue by zhaozhiming** [rstacruz/mocha-jsdom#16]
HI,
I have a JS file import other libs which use the `window` variable and I want to test it by mocha.   
I use ES6 and I must compile the test JS file by `babel`, I use the command `mocha --compilers js:babel-core/register`, but when I compile the JS there are some error as follow.  
I use mocha-jsdom but it seems no work.  
How I use mocha-jsdom to mock the 'window' variable? Thanks.  
  
JS file something like this:  

```
import xxx from 'xxx'; // use the 'window' variable

export default function foo() {
  xxx.bar(); 
}
```

test file something like this:
```
import jsdom from 'mocha-jsdom';
import foo from './foo';

describe('test' () => {
  jsdom();

  it(' test test', () => {
    foo();     
  });
});

```

error:  

```
> mocha --compilers js:babel-core/register --recursive

.../node_modules/velocity-animate/velocity.js:403
})(window);
   ^

ReferenceError: window is not defined
    at Object.<anonymous> (...node_modules/velocity-animate/velocity.js:403:4)
    at Module._compile (module.js:425:26)
    at Module._extensions..js (module.js:432:10)
    at Object.require.extensions.(anonymous function) [as .js] (.../node_modules/babel-register/lib/node.js:138:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (.../node_modules/rc-collapse/lib/openAnimation.js:9:24)
    at Module._compile (module.js:425:26)
    at Module._extensions..js (module.js:432:10)
    at Object.require.extensions.(anonymous function) [as .js] (.../node_modules/babel-register/lib/node.js:138:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (.../node_modules/rc-collapse/lib/Collapse.js:17:22)
......
```

**Comment by rstacruz** [comment]
You'll need to import it inside a `before()` block.

```js
var foo

describe('test', function () {
  jsdom()

  before(function () {
    foo = require('foo')
  })
})
```

**Comment by zhaozhiming** [comment]
It seems window have value now, but I get anther error `Error: matchMedia not present, legacy browsers require a polyfill`. What reason might cause this error？    
  
```
  1)  "before all" hook:
     Error: matchMedia not present, legacy browsers require a polyfill
      at Object.MediaQueryDispatch (node_modules/enquire.js/dist/enquire.js:226:19)
      at node_modules/enquire.js/dist/enquire.js:291:9
      at i (node_modules/enquire.js/dist/enquire.js:11:20)
      at Object.<anonymous> (node_modules/enquire.js/dist/enquire.js:21:2)
      at Object.require.extensions.(anonymous function) [as .js] (node_modules/babel-register/lib/node.js:138:7)
      at Object.<anonymous> (node_modules/react-responsive-mixin/index.js:2:28)
      at Object.require.extensions.(anonymous function) [as .js] (node_modules/babel-register/lib/node.js:138:7)
      at Object.<anonymous> (node_modules/react-slick/lib/slider.js:19:29)
      at Object.require.extensions.(anonymous function) [as .js] (node_modules/babel-register/lib/node.js:138:7)
      at Object.<anonymous> (node_modules/react-slick/lib/index.js:3:18)
      at Object.require.extensions.(anonymous function) [as .js] (node_modules/babel-register/lib/node.js:138:7)
      at Object.<anonymous> (node_modules/antd/lib/carousel/index.js:11:19)
      at Object.require.extensions.(anonymous function) [as .js] (node_modules/babel-register/lib/node.js:138:7)
      at Object.<anonymous> (node_modules/antd/lib/index.js:15:13)
      at Object.require.extensions.(anonymous function) [as .js] (node_modules/babel-register/lib/node.js:138:7)
      at loader (node_modules/babel-register/lib/node.js:130:5)
      at Object.require.extensions.(anonymous function) [as .js] (node_modules/babel-register/lib/node.js:140:7)
      at Object.done (node_modules/mocha-jsdom/index.js:70:7)
      at node_modules/jsdom/lib/jsdom.js:271:18
```

**Comment by zhaozhiming** [comment]
I give the value to window.matchMedia and it seems to work ([here](https://github.com/WickyNilliams/enquire.js/issues/82)) , thanks.

**Comment by EvHaus** [comment]
For those running into the same problem, I found an alternate solution which seems to work better.

1) `npm uninstall mocha-jsdom`
2) `npm install jsdom`
3) Create a new `setup.js` file somewhere and put this code in it:

```
import jsdom from 'jsdom';

global.document = jsdom.jsdom('<!doctype html><html><body></body></html>');
global.window = document.defaultView;
global.navigator = global.window.navigator;
```

4) Load this file before all your mocha tests via `mocha -r test/setup.js`

Then you can import everything without issue and jsdom will be automatically loaded for all your tests.

**Comment by FullStackAlex** [comment]
@EvHaus 
thank you for the hint in the right direction. Though you actually don't need the global.window declaration as global window and document variables are created by jsdom-global itself.
node_modules/jsdom-global/index.js:

```js
/*
 * enables jsdom globally.
 */

var KEYS = require('./keys')

var defaultHtml = '<!doctype html><html><head><meta charset="utf-8">' +
  '</head><body></body></html>'

module.exports = function globalJsdom (html, options) {
  if (html === undefined) {
    html = defaultHtml
  }

  if (options === undefined) {
    options = {}
  }

  // Idempotency
  if (global.navigator &&
    global.navigator.userAgent &&
    global.navigator.userAgent.indexOf('Node.js') > -1 &&
    global.document &&
    typeof global.document.destroy === 'function') {
    return global.document.destroy
  }

  var jsdom = require('jsdom')
  var document = new jsdom.JSDOM(html, options)
  var window = document.window

  KEYS.forEach(function (key) {
    global[key] = window[key]
  })

  global.document = window.document
  global.window = window
  window.console = global.console
  document.destroy = cleanup

  function cleanup () {
    KEYS.forEach(function (key) { delete global[key] })
  }

  return cleanup
}

```

so my setup.js looks just like this:
```js
let jsdom = require('jsdom-global')();

global.customData = {some:stuff};

//https://github.com/vuejs/vue-cli/issues/2128
window.Date = Date;
```
