### ISSUE TITLE
jquery requires a window with document?????

### ISSUE THREAD

**Issue by kokokele** [rstacruz/mocha-jsdom#20]
code:
```js
var chai = require('chai')
var jsdom = require('mocha-jsdom')

var expect = chai.expect;

describe('jquery', function () {
  var $
  jsdom()

  before(function () {
    $ = require('jquery')
  })

  it('creating elements works', function () {
    var div = $('<div>hello <b>world</b></div>')
    expect(div.html()).to.eql('hello <b>world</b>')
  })

  it('lookup works', function () {
    document.body.innerHTML = '<div>hola</div>'
    expect($('div').html()).eql('hola')
  })
})


```

## test out :

```
jquery
    1) creating elements works
    2) lookup works


  0 passing (789ms)
  2 failing

  1) jquery creating elements works:
     Error: jQuery requires a window with a document
      at module.exports (node_modules/jquery/dist/jquery.js:29:12)

      at Context.<anonymous> (test.js:17:15)

  2) jquery lookup works:
     Error: jQuery requires a window with a document
      at module.exports (node_modules/jquery/dist/jquery.js:29:12)
      at Context.<anonymous> (test.js:23:12)

```

**Comment by rmisio** [comment]
I'm getting the same issue. How did you fix it?

**Comment by rstacruz** [comment]
Can you try with github.com/rstacruz/jsdom-global?

**Comment by rmisio** [comment]
I get the same error. Here's the code I'm using:

```
import 'jsdom-global/register';
import $ from 'jquery';
import { expect } from 'chai';
import { describe, it } from 'mocha';

describe('jquery', function () {
  it('creating elements works', function () {
    const div = $('<div>hello <b>world</b></div>');
    expect(div.html()).to.eql('hello <b>world</b>');
  });
});
```
