### ISSUE TITLE
Introduced the file contains the jquery complains

### ISSUE THREAD

**Issue by kokokele** [rstacruz/mocha-jsdom#21]
## http.js file:
```js

import $ from 'jquery'

module.exports = function(p, param, callback) {
    var _url = "https://saas.hr/index.php?r=" + p + "&username=312377136@qq.com";
    var _port = 80;
  
    $.ajax({
        type : "post",

        url : _url,
        data : param,
        jsonp : "callback",


        success: function(data){
            if (data.code && data.code == 1) {
                 if(callback) callback(data.data);

            } else {

                if(data.msg){
                    toastr.error(data.msg);
                }
            }

        },
        error: function(data){

        }
    });



}

```

## test file

```js
var chai = require('chai')
var expect = chai.expect;

var jsdom = require('mocha-jsdom')
jsdom();

import http from '../src/utils/http'


describe('add', function() {

    it("test http", (done) => {
        http('aa', {}, data=>{
            

        })
    });
});
```

## test out
```
add
https://saas.hr/index.php?r=aa&username=312377136@qq.com  {}
    1) test http


  0 passing (197ms)
  1 failing

  1) add test http:
     `TypeError: _jquery2.default.ajax is not a function`

      at module.exports (http.js:35:7)
      at Context.<anonymous> (test.js:33:9)

```

**Comment by rstacruz** [comment]
Try:

var http
before(() => { http = require('../src/utils/http') }

And:

var $ = require('jquery')
// instead of import

Also please try http://npmjs.com/jsdom-global instead, they successor of
mocha-jsdom.

**Comment by kokokele** [comment]
thx.
