### ISSUE TITLE
TypeError: before is not a function

### ISSUE THREAD

**Issue by jurosh** [rstacruz/mocha-jsdom#26]
When running:
```
const jsdom = require('mocha-jsdom');
jsdom();
```

I've got this error:
```
...web\node_modules\mocha-jsdom\index.js:45
  before(function (next) {
  ^
TypeError: before is not a function
    at module.exports (...web\node_modules\mocha-jsdom\index.js:45:3)
    at Object.<anonymous> (...web\test\test-setup.ts:9:1)
    at Module._compile (module.js:541:32)
    at Module.m._compile (...web\node_modules\ts-node\src\index.ts:385:23)
    at Module._extensions..js (module.js:550:10)
    at Object.require.extensions.(anonymous function) [as .ts] (...web\node_modules\ts-node\src\index.ts:388:12)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)`
    at ...web\node_modules\mocha\bin\_mocha:355:3
    at Array.forEach (native)
    at Object.<anonymous> (...web\node_modules\mocha\bin\_mocha:354:10)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (node.js:348:7)
    at startup (node.js:140:9)
    at node.js:463:3
```

mocha.opts
```
--require ignore-styles
--require test/test-setup.ts
--recursive
--compilers ts:ts-node/register
--compilers tsx:ts-node/register
```

test-setup:
```
import * as chai from 'chai';
import * as chaiEnzyme from 'chai-enzyme';
import * as sinonChai from 'sinon-chai';
import * as mockCssModules from 'mock-css-modules';

const jsdom = require('mocha-jsdom');
jsdom(); // this fails
....
```

Maybe I've did some configuration incorrectly, but without mocha-jsom tests are running fine... can you please tak a look..

Node:  `v6.2.2` on Windows

**Comment by Pavel-Durov** [comment]
I'm having the same issue - running on Windows 7 and Ubuntu.

Node: 8.9.1
Npm: 5.5.1

**Comment by valishah** [comment]
Hi, I'm facing the same issue with Node : v8.11.2 and Machine : Mac 
Mocha : v5.2.0. 
Any specific things to be done to fix this?

**Comment by rstacruz** [comment]
Consider https://yarn.pm/jsdom-global instead.

**Comment by rstacruz** [comment]
You can't use mocha-jsdom in `--require`d files. See: https://github.com/mochajs/mocha/issues/1762#issuecomment-115234936

**Comment by rstacruz** [comment]
Also, consider [jsdom-global](https://yarnpkg.com/en/package/jsdom-global) instead!
